namespace RAMBaseDB.Domain.Metadata;

using System.Collections.Generic;

/// <summary>
/// Represents the serialized structure of a metadata table file created by the RAMBaseDB UI.
/// </summary>
public sealed class TableMetadataDocument
{
    public string DatabaseName { get; set; } = string.Empty;
    public string TableName { get; set; } = string.Empty;
    public List<FieldMetadataDocument> Fields { get; set; } = new();
}

/// <summary>
/// Describes a single field entry inside a table metadata document.
/// </summary>
public sealed class FieldMetadataDocument
{
    public string Name { get; set; } = string.Empty;
    public string DataType { get; set; } = string.Empty;
    public int Length { get; set; }
    public bool AllowBlank { get; set; }
    public bool AutoGenerated { get; set; }
}
